<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ahamadunnisa18072002gmail.com_verify-_37dbc1</name>
   <tag></tag>
   <elementGuidId>3fd60199-d868-4547-8dae-12ead5371e01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.verify-code__input-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8525d69-a1a3-423a-bb12-9ff8d910f89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a431e2b-e42d-492e-973e-08b837d240f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>bbc742ec-5d8b-44f9-a091-f211ced1685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1dc4bfb6-ec26-48c2-a8cc-47b017733fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verify-code__input-item</value>
      <webElementGuid>ede816e3-81f5-4efb-a058-f95bc22ca89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-app&quot;)/div[@class=&quot;login-layout full-width-wrapper&quot;]/div[@class=&quot;forms-layout__left&quot;]/div[@class=&quot;full-width-wrapper verify-code&quot;]/div[@class=&quot;verify-code__wrapper&quot;]/div[@class=&quot;verify-code__input-group&quot;]/input[@class=&quot;verify-code__input-item&quot;]</value>
      <webElementGuid>0be9e410-cbf2-4496-ad98-a05c8d7c7c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search task by name</value>
      <webElementGuid>784e5601-60eb-4765-91fb-4913de15762c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>5ae295fa-0a9a-42ea-9702-6bb31f1ab4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/div/div/div/div/div[3]/input</value>
      <webElementGuid>296ff82a-0ba0-4b12-b662-d659a764ec9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b1cb2216-ca2a-434e-8780-c7efc291a601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a500c568-2262-4948-8289-d650a9e9a10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>faa8156a-847c-426c-9108-d3bf456b757e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>7d61b2ef-7f2e-47a1-9764-6aae65e1e543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>2c57712e-3f05-4e05-8dee-db2b3bb7bd25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search task by name']</value>
      <webElementGuid>a1f685d9-f279-4277-8077-5232f8e8c42e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
