<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ahamadunnisa18072002gmail.com_verify-_37dbc1</name>
   <tag></tag>
   <elementGuidId>7ff9f13b-7787-4422-8e31-2a48e25c8764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.verify-code__input-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dabccca8-8171-46bb-bbb5-cc1943147466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30a9e91b-95d0-4dc9-8e51-15d9fde0a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>9a4e37e9-f2ce-4b41-8315-d191a878afc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3eb2f0bb-4f61-414a-b661-a7e3f2b69049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verify-code__input-item</value>
      <webElementGuid>a9844135-1d27-40a5-b2a7-0782fc1baecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-app&quot;)/div[@class=&quot;forms-layout full-width-wrapper&quot;]/div[@class=&quot;forms-layout__left&quot;]/div[@class=&quot;full-width-wrapper verify-code&quot;]/div[@class=&quot;verify-code__wrapper&quot;]/div[@class=&quot;verify-code__input-group&quot;]/input[@class=&quot;verify-code__input-item&quot;]</value>
      <webElementGuid>d4f2e2c1-b3b9-4fff-ae14-177a0c2aed69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>6908bf08-0e77-48d4-b742-9753f09aaca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/div/div/div/div/div[3]/input</value>
      <webElementGuid>db7e7929-a5d5-4860-bbef-eabee701650e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a34e0c72-df6e-4ec6-ad6d-c09e21083d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>098ed618-e262-4429-8789-0cdc43378ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
