<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_Company</name>
   <tag></tag>
   <elementGuidId>12d797ad-1fc6-456d-8540-be80790b3443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d5faf74-8273-4605-a7d2-10e8e6873ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>4500810d-9a1d-431a-9eb7-8bac047a5cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>479ca583-973a-475a-b55b-99cf05d042a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5926f294-3e00-45b2-8f9f-a36432c5e1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>fe570067-0207-4ba4-b55c-e28019b8f5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Company&quot;)</value>
      <webElementGuid>1ae157b7-99f7-4449-861c-806be17e1536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Company']</value>
      <webElementGuid>02e9a239-3c38-4144-87f2-55f557487281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/div/div/div/div[2]/div[2]/div[4]/div/input</value>
      <webElementGuid>ef1099cd-51e9-47c5-817f-6545fca0def4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>2913710d-c952-43c9-903a-0ae01a608147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Company' and @placeholder = 'Company' and @type = 'text']</value>
      <webElementGuid>66048a4e-c02a-4d9a-9606-064342ff6930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
