<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See all features</name>
   <tag></tag>
   <elementGuidId>916813a4-7554-4ed9-9eb6-cfc04f89061c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-app']/section/header/div[3]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.header > div.header-submenu > div.header-submenu__features > div.header-submenu__item-icon.header-submenu__item-icon--right > a.link-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30e361b9-be13-457f-b485-24b203cc7479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/all-actitime-features</value>
      <webElementGuid>08b72883-7abb-415d-9d61-6754f6645f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-arrow</value>
      <webElementGuid>522273bb-5fd1-4d7c-9f69-a29b1db67548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See all features</value>
      <webElementGuid>f9002f3e-2ccb-465b-bd4b-161a80980bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-app&quot;)/section[@class=&quot;header-wrap&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header-submenu&quot;]/div[@class=&quot;header-submenu__features&quot;]/div[@class=&quot;header-submenu__item-icon header-submenu__item-icon--right&quot;]/a[@class=&quot;link-arrow&quot;]</value>
      <webElementGuid>b3d19dd1-f89c-4fcc-ae61-3121f73e8b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/section/header/div[3]/div/div[2]/a</value>
      <webElementGuid>5d5bd98d-a970-4fba-925f-245290424eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Datashseet PDF'])[7]/following::a[1]</value>
      <webElementGuid>2ce642ec-69f3-4cb6-b092-712b5bf45083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrations'])[7]/following::a[2]</value>
      <webElementGuid>16874423-10e3-4874-9f19-f6d1a9722e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture'])[7]/preceding::a[4]</value>
      <webElementGuid>18d18b89-4719-49fc-8b56-496c3fc5fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/all-actitime-features')])[7]</value>
      <webElementGuid>d694e8c3-8c59-4fe7-84e8-4d1a45f9a1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
      <webElementGuid>b6dbf5be-ee9e-4b14-9b92-8a1bcb3b1a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/all-actitime-features' and (text() = 'See all features' or . = 'See all features')]</value>
      <webElementGuid>8a2f589e-4942-412b-afb5-a3ec913eb8a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
