<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time Tracking Reports  Data Analysis Pr_9e3739</name>
   <tag></tag>
   <elementGuidId>fdb4541d-80db-4139-be40-aef3db56ae95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-app']/section/header/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.header > div.header-submenu > div.header-submenu__features > div.header-submenu__items</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acb6ce4c-1ada-42e7-be22-4fe656411a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-submenu__items</value>
      <webElementGuid>188866bb-aea0-4133-9c12-52b0ca565182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Time Tracking Reports &amp; Data Analysis Project Tracking Customer Care Billing &amp; Invoicing Team Management Workflow Integrations  Product Datashseet PDF</value>
      <webElementGuid>c8c25185-26a6-4cfe-9699-171511c4dd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-app&quot;)/section[@class=&quot;header-wrap&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header-submenu&quot;]/div[@class=&quot;header-submenu__features&quot;]/div[@class=&quot;header-submenu__items&quot;]</value>
      <webElementGuid>04b668ec-c934-4ea8-b841-f25f78ab08bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/section/header/div[3]/div/div</value>
      <webElementGuid>b63b04d0-161c-43c6-85a0-5b1512980ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all guides and resources'])[6]/following::div[17]</value>
      <webElementGuid>a09f4937-e9ea-4370-94a7-0fc7a8edb559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For E-commerce'])[6]/following::div[31]</value>
      <webElementGuid>60448d8d-942b-4806-9930-eec7063afd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>3656f119-0524-439c-905c-205d2fbff767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Time Tracking Reports &amp; Data Analysis Project Tracking Customer Care Billing &amp; Invoicing Team Management Workflow Integrations  Product Datashseet PDF' or . = ' Time Tracking Reports &amp; Data Analysis Project Tracking Customer Care Billing &amp; Invoicing Team Management Workflow Integrations  Product Datashseet PDF')]</value>
      <webElementGuid>0b4cd66d-d7e1-4bc0-91e1-22b05c9ad040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
