<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>5896794a-fcef-478c-8577-f0a5b9a29418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.containers-EnterTT-ETTTaskPanel-trigger--ANgIUi1t</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14bd0769-191c-4f7d-9f8e-d8d4c0cd8521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>containers-EnterTT-ETTTaskPanel-trigger--ANgIUi1t</value>
      <webElementGuid>398bb953-0e5d-441a-9f60-a1b6263ae594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>baseTooltipId</value>
      <webElementGuid>bdb573e2-a0d2-4870-9e07-1a75e9043325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>Add tasks to the timesheet</value>
      <webElementGuid>ee69fd68-3edc-475a-b0e8-23289c1c73fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21bd4b30-5716-40d0-b93e-899ac350ac0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>136abaf4-9536-48cd-b3df-f80523c35c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atNextAppRoot&quot;)/div[@class=&quot;containers-EnterTT-entertt---VveRP30 containers-EnterTT-calendar--3f4ekZYt&quot;]/div[@class=&quot;containers-EnterTT-timesheetControls--1vxzPCwE containers-EnterTT-table--aosIocub&quot;]/div[@class=&quot;containers-EnterTT-column--yn7lG-49 containers-EnterTT-taskSelector--3n6kIam5&quot;]/div[1]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-taskPanel--1uV7BlSA&quot;]/div[@class=&quot;components-Dropdown-trigger--1w6PGjU6&quot;]/button[@class=&quot;containers-EnterTT-ETTTaskPanel-trigger--ANgIUi1t&quot;]</value>
      <webElementGuid>3f38e065-7cfb-4a8a-8985-11c39d5da4bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div/button</value>
      <webElementGuid>6922a3e6-a604-42a8-a605-1baa09a76030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time-Track of Nandhini, Gadiparthi'])[1]/following::button[1]</value>
      <webElementGuid>941db424-ae43-475c-b650-67a674db8bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheet'])[1]/following::button[1]</value>
      <webElementGuid>e5abc81e-3a0f-4f38-b12d-718d336617a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug 07 - Aug 13, 2023'])[1]/preceding::button[1]</value>
      <webElementGuid>ea55ed45-63b0-4712-a93a-6530343786a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Week for Approval'])[1]/preceding::button[1]</value>
      <webElementGuid>e2196aad-9479-4b52-8ae6-68dd6ae11f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>b458b19b-9dd6-4f76-84d9-e3a616e4a49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>679b7483-2409-4554-ba3a-dea488fb6703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '+' or . = '+')]</value>
      <webElementGuid>77abf8c4-6fc7-477d-9e68-dd1f3c0662e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time-Track of Sireesha, Nidamanuri'])[1]/following::button[1]</value>
      <webElementGuid>e62fc4ff-99e6-41d2-b7f2-f9906a995ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 31 - Aug 06, 2023'])[1]/preceding::button[1]</value>
      <webElementGuid>c5f93f41-2148-464b-8f33-3eff01e62381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
