<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Calls (already added)Our companyManagement</name>
   <tag></tag>
   <elementGuidId>7a6272a4-1998-4085-8c4d-916a9c8c3f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20c36e07-5575-45b1-b3cc-7418b52004de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components-TaskItem-wrapper--2UFEfEz6 components-TaskItem-hoverable--1dAv1uDr</value>
      <webElementGuid>688aa0ac-a64f-4444-ba29-1ac9c00110bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>Click to view this task on the timesheet</value>
      <webElementGuid>4f06ba85-db30-4a87-9eb4-6d2e2943d4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>baseTooltipId</value>
      <webElementGuid>a53fde3f-ca0b-4cfd-81e8-a2ef8866283c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip-disable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cfe7636-9e47-4e69-b8ff-da372c837a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calls (already added)Our company/Management</value>
      <webElementGuid>dc81ca13-0061-4aec-a860-85bfa5027764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atNextAppRoot&quot;)/div[@class=&quot;containers-EnterTT-entertt---VveRP30 containers-EnterTT-calendar--3f4ekZYt&quot;]/div[@class=&quot;containers-EnterTT-timesheetControls--1vxzPCwE containers-EnterTT-table--aosIocub&quot;]/div[@class=&quot;containers-EnterTT-column--yn7lG-49 containers-EnterTT-taskSelector--3n6kIam5&quot;]/div[1]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-taskPanel--1uV7BlSA&quot;]/div[@class=&quot;components-PopupWrapper-popup--q_WJegMT components-Dropdown-dropdownPopup--3o-HLxx4 containers-EnterTT-ETTTaskPanel-popupContent--2wxHgNkj&quot;]/div[1]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-tabContent--HJslJklo&quot;]/div[@class=&quot;ScrollbarsCustom&quot;]/div[@class=&quot;ScrollbarsCustom-Wrapper&quot;]/div[1]/div[@class=&quot;ScrollbarsCustom-Content&quot;]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-RecentTasksSection-section--3cL6UL-_&quot;]/div[@class=&quot;components-TaskItem-wrapper--2UFEfEz6 components-TaskItem-hoverable--1dAv1uDr&quot;]</value>
      <webElementGuid>5e167f13-3d43-42c7-884b-7a3e991f4578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[5]</value>
      <webElementGuid>47e7efdb-b6a0-4f79-b8e4-9f46a6164071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight operations'])[1]/following::div[1]</value>
      <webElementGuid>3b5158e0-9056-4f32-a602-5362dabff12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::div[1]</value>
      <webElementGuid>8bbbf887-3e47-469a-a25a-ce8911f2c8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[5]</value>
      <webElementGuid>4c256e80-3c03-4bb9-bcae-b5822eda693f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Calls (already added)Our company/Management' or . = 'Calls (already added)Our company/Management')]</value>
      <webElementGuid>a2c47639-4d72-42cf-b8c1-a83d2ccb08eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
