<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time-Track</name>
   <tag></tag>
   <elementGuidId>81c58d2f-ed6d-4259-ada9-32694fef49ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='topnav']/tbody/tr/td[3]/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7fad87a-e5f3-4d42-89f8-cb2a04c9c370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7ce8c658-ca64-4adf-9aa8-c4cabe8b5bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time-Track</value>
      <webElementGuid>00ae03a9-d3dd-4a38-a375-1816c3fad09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav&quot;)/tbody[1]/tr[1]/td[@class=&quot;navItem preventPanelsHiding navCell relative selected popup_submenu_container&quot;]/a[@class=&quot;content selected tt&quot;]/div[@class=&quot;label&quot;]</value>
      <webElementGuid>39b72d7f-b026-421e-95aa-b812f57e174b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='topnav']/tbody/tr/td[3]/a/div[2]</value>
      <webElementGuid>90d9446c-cce3-40ae-94f5-cf007c491e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more in User Guide'])[1]/following::div[6]</value>
      <webElementGuid>4cb3fbaf-7104-40a6-aad1-6092af428282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage System Settings'])[1]/following::div[9]</value>
      <webElementGuid>6e5c9768-93b8-4968-a66b-75244421dc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Time-Track'])[2]/preceding::div[2]</value>
      <webElementGuid>bf2ed54c-a4f7-49c2-a480-71e1e32bf8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Time-Track'])[1]/preceding::div[3]</value>
      <webElementGuid>1051760b-ac34-412a-840e-2c6838e19f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time-Track']/parent::*</value>
      <webElementGuid>6e35c352-dd6a-42e5-89f8-81c79aa7f6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>01d03c50-5f13-4351-8268-acd52d0e0c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Time-Track' or . = 'Time-Track')]</value>
      <webElementGuid>e1727bea-835a-4f44-8261-7c6ac878261f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
