<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No deadline_containers-EnterTT-ETTTim_28ab9f</name>
   <tag></tag>
   <elementGuidId>7f16bedb-99b7-461d-bc6c-027e968f9dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-inputWrapper--35FAaz_S.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-visible--2ntBVd2U.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-pointerHover--1P0OCdpF > input.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9243fccf-d502-4b51-8548-1d2783c5ffb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47a41907-2971-49a3-984b-d05e968a5395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h</value>
      <webElementGuid>92c84177-fd3f-4616-990c-6a71396bfb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b1cc3a93-3577-4932-bab3-f7c065bb999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow-keyboard-navigation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>647d2ef0-6c49-41d6-9529-f2df1464fa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2:00</value>
      <webElementGuid>d92d270a-4972-4638-b929-914a6d202812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;127&quot;)/div[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-RecordDaysSection-timeSection--1e5l-_Xh&quot;]/div[@class=&quot;components-TableCell-tableCell--Ot35iU8P containers-EnterTT-ETTTimesheet-TTCell-ttCell--19clds4b containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-timeCell--1KgpeVk2 containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-today--3j_itX8H containers-EnterTT-ETTTimesheet-TTCell-pointerHover--3SqEpbqV&quot;]/div[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-inputWrapper--35FAaz_S containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-visible--2ntBVd2U containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-pointerHover--1P0OCdpF&quot;]/input[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h&quot;]</value>
      <webElementGuid>53787227-7dd8-4dbb-b2d1-e29092f22683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search task by name</value>
      <webElementGuid>aa60ef7f-6e87-4085-801d-5f75c0cf6dc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>84dffdfc-6186-49e4-9a9b-810cc80786f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='127']/div[2]/div[2]/div/input</value>
      <webElementGuid>17e7f67e-a6a4-42dc-aa0f-b6af62748e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>35cf932f-efc7-4623-8cb2-82c18da267eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a291e9f5-0c38-41cc-a197-26bba86fa574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>edc741b6-4277-4d5e-be3a-78e131cb4ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>add440ab-4807-422f-a455-b82a4ed1c593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>07d0face-fdc6-4ba1-a8a2-2aa20d3dd7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search task by name']</value>
      <webElementGuid>d68a19a2-7e5e-4f10-920f-b9f9902d9f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>920493cc-c470-425e-b8ca-5e58c0ca3225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='130']/div[2]/div[7]/div/input</value>
      <webElementGuid>9bd8df37-2688-4767-b5bb-d2aeedf1138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[7]/div/input</value>
      <webElementGuid>385720ea-a84b-4f01-bce6-d9c5838d4e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='127']/div[2]/div[7]/div/input</value>
      <webElementGuid>104f0721-79bb-462f-87c1-15fdb9bf57ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>5da40b8f-64e9-49d8-b952-9685d93f6e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '0:00']</value>
      <webElementGuid>bbe9af71-8a35-4431-a1e5-66860a0a1600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='2:00']</value>
      <webElementGuid>05f5ead6-ff2f-4f73-b0d4-ef41784a6ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='127']/div[2]/div[6]/div/input</value>
      <webElementGuid>e7f27260-5c83-485c-9085-864cab9073ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>92bb1e7b-1e95-435c-9b33-3f6eba2484bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
