<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No deadline_containers-EnterTT-ETTTim_28ab9f_1</name>
   <tag></tag>
   <elementGuidId>b115a878-0e78-4982-841c-9f8bad2907a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-inputWrapper--35FAaz_S.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-visible--2ntBVd2U.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-focus--1v-reavm > input.containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1227f962-0597-418d-8533-076efa7c31f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90af3ed7-2284-4279-b896-35f3b201a9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h</value>
      <webElementGuid>e164aa77-7bd2-407f-8861-157ec44a220d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0:00</value>
      <webElementGuid>4c61f2bc-8b44-4c1a-9b58-39944cd06d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8a695846-3703-4c8f-8a26-46d230d3677a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow-keyboard-navigation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd8a0b8b-954f-4911-8253-ed9092205afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;127&quot;)/div[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-RecordDaysSection-timeSection--1e5l-_Xh&quot;]/div[@class=&quot;components-TableCell-tableCell--Ot35iU8P containers-EnterTT-ETTTimesheet-TTCell-ttCell--19clds4b containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-timeCell--1KgpeVk2 containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-today--3j_itX8H containers-EnterTT-ETTTimesheet-TTCell-active--3TU6rau6&quot;]/div[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-inputWrapper--35FAaz_S containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-visible--2ntBVd2U containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-focus--1v-reavm&quot;]/input[@class=&quot;containers-EnterTT-ETTTimesheet-TasksSection-TimeCell-input--2TrVpi5h&quot;]</value>
      <webElementGuid>b37f90fc-949b-49ba-8085-e0c1acb66340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>4235ba45-79d1-4ebe-bb2b-1e6c95c14c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='127']/div[2]/div[2]/div/input</value>
      <webElementGuid>eb70c50b-6557-4d41-95e1-2f71b121f7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1ad89b60-b938-4eb7-8459-cfd4377bc1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '0:00']</value>
      <webElementGuid>43c3874e-1c40-4a4c-90bb-381a6b758090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>5d06aa06-40ce-4408-a3ef-51f94a7ce260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='127']/div[2]/div[6]/div/input</value>
      <webElementGuid>387d06f9-f180-44d6-8946-ac463900b960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>32e63d97-2c69-4940-896b-0645b8fe5859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
