<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Management</name>
   <tag></tag>
   <elementGuidId>da30e991-a866-4bcc-b696-808fe3adb918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[4]/div[2]/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adb20204-a5b8-49d1-8e3f-b858667b1c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components-TruncatedText-oneLine--Jmk2Gxm5</value>
      <webElementGuid>15c62fc5-04ea-442d-a720-2c3b4664b0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management</value>
      <webElementGuid>4dbdfbcb-2909-4da8-8272-25b5970ff83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atNextAppRoot&quot;)/div[@class=&quot;containers-EnterTT-entertt---VveRP30 containers-EnterTT-calendar--3f4ekZYt&quot;]/div[@class=&quot;containers-EnterTT-timesheetControls--1vxzPCwE containers-EnterTT-table--aosIocub&quot;]/div[@class=&quot;containers-EnterTT-column--yn7lG-49 containers-EnterTT-taskSelector--3n6kIam5&quot;]/div[1]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-taskPanel--1uV7BlSA&quot;]/div[@class=&quot;components-PopupWrapper-popup--q_WJegMT components-Dropdown-dropdownPopup--3o-HLxx4 containers-EnterTT-ETTTaskPanel-popupContent--2wxHgNkj&quot;]/div[1]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-tabContent--HJslJklo&quot;]/div[@class=&quot;ScrollbarsCustom&quot;]/div[@class=&quot;ScrollbarsCustom-Wrapper&quot;]/div[1]/div[@class=&quot;ScrollbarsCustom-Content&quot;]/div[@class=&quot;containers-EnterTT-ETTTaskPanel-RecentTasksSection-section--3cL6UL-_&quot;]/div[@class=&quot;components-TaskItem-wrapper--2UFEfEz6 components-TaskItem-hoverable--1dAv1uDr&quot;]/div[@class=&quot;components-CPLine-wrapper--L9fTfURG&quot;]/span[@class=&quot;components-TruncatedText-truncatedText--1iVivIkq&quot;]/span[@class=&quot;components-TruncatedText-oneLine--Jmk2Gxm5&quot;]</value>
      <webElementGuid>f7914211-f679-46b2-a3a5-d56a6f375516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='atNextAppRoot']/div/div[3]/div/div/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[4]/div[2]/span[3]/span</value>
      <webElementGuid>6ccf5ec6-7d34-45f6-95d4-788b6a57242a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::span[2]</value>
      <webElementGuid>7f2c0cb2-7e93-4565-9a0f-acada33da2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our company'])[1]/following::span[3]</value>
      <webElementGuid>6b87b08f-83b2-4f46-80d5-f04c8660a9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capacity planning: Q2'])[1]/preceding::span[1]</value>
      <webElementGuid>81a2528d-46a7-48e8-9c78-b99209bab439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our company'])[2]/preceding::span[3]</value>
      <webElementGuid>0926241d-767b-4b57-b9c0-eae108cc3e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Management']/parent::*</value>
      <webElementGuid>d41d6b18-8154-48e2-a6d1-3ebcd7202d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span[3]/span</value>
      <webElementGuid>b2487294-697d-473e-9044-1303e4d6cd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Management' or . = 'Management')]</value>
      <webElementGuid>0a944c64-4eb7-4df0-9a39-c44b80dcdba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
