<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Using actiTIME</name>
   <tag></tag>
   <elementGuidId>6eb5df21-43e0-4d51-aeb5-74d23de41fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-app']/div/div/div[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.request-demo__button.button.request-demo-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52c20f6f-643e-4041-a2c1-23357365e661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/free-online-trial</value>
      <webElementGuid>40bf776b-079c-45c3-af75-3394b62933be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>request-demo__button button request-demo-button</value>
      <webElementGuid>7849bbc9-44dd-4f2f-97f0-e4ae0a30729e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Using actiTIME</value>
      <webElementGuid>5e0c9199-55e0-433e-bc17-2195874eefa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-app&quot;)/div[@class=&quot;default-layout&quot;]/div[@class=&quot;full-width-wrapper feature&quot;]/div[@class=&quot;feature__request-demo&quot;]/div[@class=&quot;request-demo__container&quot;]/a[@class=&quot;request-demo__button button request-demo-button&quot;]</value>
      <webElementGuid>e16e5256-aab8-4681-ba1c-eebe0a4714ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/div/div/div[4]/div/a</value>
      <webElementGuid>e826dbd2-9ef3-47f5-a609-fddc35760562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start Using actiTIME')]</value>
      <webElementGuid>7a7c5e6d-4e05-4ba9-8b4f-5cc550ecfff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready to bring'])[1]/following::a[1]</value>
      <webElementGuid>255ad1a5-07f2-45a9-b550-e545152e12d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Datashseet PDF'])[8]/preceding::a[3]</value>
      <webElementGuid>6570a166-6fa3-4c65-af70-517b1a930d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Using actiTIME']/parent::*</value>
      <webElementGuid>1dbe535f-0e22-4014-ac4c-99e714f9f437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/free-online-trial')])[25]</value>
      <webElementGuid>b11dbac4-6da8-441b-96ec-babf53f6a44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>6fe62687-af77-4f34-9f19-a6a06db91979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/free-online-trial' and (text() = 'Start Using actiTIME' or . = 'Start Using actiTIME')]</value>
      <webElementGuid>c1b54bc4-d076-4438-85c3-33b5bd0d6813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
